LIBNAME MODEL "/efs-MAIO/Team/promo_opt/MktMixPP/2024 Planning/Belsomra/output/HCC/MODEL_DATASET";
OPTIONS COMPRESS=YES NOLABEL NOCENTER ERROR=1 MACROGEN SYMBOLGEN;

PROC DATASETS LIBRARY=WORK NOLIST KILL;
	RUN;
QUIT;

PROC STANDARD DATA=MODEL.ADS_FN_BELSOMRA_MDB_Feb21_JAN23(where= (yearmo >= 202102)) MEAN=0 REPLACE 
		OUT=MODEL.DM_BELSOMRA_MDB_FEB21_JAN23;
	BY DMANAME;
	VAR hcp: hcc: pp:;
RUN;