LIBNAME DEEPD "\\WPUSHH01\DINFOPLN\MARKETING MIX PI\INVOPT\P2 2014 AB\PROMO\DIABETES DEEP DIVE\SAS WORK";
ODS HTML CLOSE; ODS HTML;

******************************************************************************************************************************************;
* COMPUTE ADSTOCK AND EXPLORE REGRESSION MODELS USING LONG GRAPH DATA. 2009/10 CATEGORY/SUB-CATEGORY SPENDS ARE INFERRD FROM 2011 WEIGHTS ;
******************************************************************************************************************************************;

* Import new DTC spend from Draft.;
* BRING MEDIA SPEND (from Draft) EXCEL DATA INTO SAS FROM SPREADSHEETS;
%MACRO IMPEM2 (FNAME,RNAME);
	PROC IMPORT OUT= WORK.&FNAME 
	DATAFILE= "\\WPUSHH01\DINFOPLN\Marketing Mix PI\InvOpt\P2 2014 AB\Promo\Diabetes Deep Dive\OtherData\Monthly_Paid_Media_Spend_by_Year_3_4_13.xlsx"
	DBMS=EXCEL REPLACE; RANGE="&RNAME"; GETNAMES=YES; MIXED=NO; SCANTEXT=YES; USEDATE=YES; SCANTIME=YES; RUN;
%MEND;
%IMPEM2 (MSPEND,MEDIA$); *PROMOTION SPEND for Media;

* integrate with combo and inferred datasets.;
proc sort data=deepd.combo out=combo; by sas_date; run;
proc sort data=deepd.inferred out=inferred; by sas_date; run;
proc sort data=mspend; by sas_date; run;
data combo2;
  merge combo(in=a) mspend(in=b);
  by sas_date;
  if a;
run;
data inferred2;
  merge inferred(in=a) mspend(in=b);
  by sas_date;
  if a;
run;
/*
* store as permanent dataset;
data deepd.combo; set combo2; run;
data deepd.inferred; set inferred2; run;
*/


%LET DECAY=0.5;
%LET HALFLF=1;

/* %MACRO KOYCK(DECAY,HALFLF);*/
DATA STOCK_0912 (DROP=I);
	SET DEEPD.INFERRED (WHERE=(SAS_DATE<'1-JAN-2013'D));
	ARRAY NEWP {18}
		  CI_2_COMM_PROGRAMS_AND_CAMPAIGNS CI_1_CUSTOMER_RESOURCES CI_3_MEDICAL_EDUCATION CI_6_SAMPLES_COUPONS_VOUCHERS 
		  SCI_2_ADVERTISING_PROGRAMS SCI_2_MCM_CAMPAIGN_EXECUTION SCI_1_DISEASE_TREATMENT_RSCRS SCI_1_PRODUCT_PROMO_RESOURCES 
		  SCI_3_LECTURE_PROGRAMS SCI_3_MMFS SCI_6_COUPONS_VOUCHERS SCI_6_PRODUCT_SAMPLES SCI_6_SAMPLES_DIST_FULFILLMENT TOTAL_PROMO
		  SCI_DIRECT DETAILS SAMPLES MEDIA_DRF;
	ARRAY STOCKS {18}
		  STK&HALFLF._C_2_CPCS STK&HALFLF._C_1_CRS STK&HALFLF._C_3_ME STK&HALFLF._C_6_SCVS STK&HALFLF._SC_2_AP STK&HALFLF._SC_2_MCM_CE
		  STK&HALFLF._SC_1_DTRS STK&HALFLF._SC_1_PPRS STK&HALFLF._SC_3_LPS STK&HALFLF._SC_3_MMFS STK&HALFLF._SC_6_CV STK&HALFLF._SC_6_PS
		  STK&HALFLF._SC_6_SAMFUL STK&HALFLF._TOTAL_C STK&HALFLF._SC_DIRECT STK&HALFLF._DETAILS STK&HALFLF._SAMPLES 
          STK&HALFLF._MEDIA_DRF;
	RETAIN STOCKS;
	DO I=1 TO DIM(NEWP);
		IF SAS_DATE='1-JAN-2009'D THEN STOCKS(I)=0;
		STOCKS(I)=NEWP(I) + &DECAY. * STOCKS(I);
	END;
	STK&HALFLF._SC_DIRECT2=STK&HALFLF._SC_DIRECT*STK&HALFLF._SC_DIRECT;
	IF '1-JAN-2009'D <= SAS_DATE <= '1-FEB-2009'D THEN FIRST2=1; ELSE FIRST2=0;
	IF SAS_DATE = '1-APR-2010'D THEN COMET=1; ELSE COMET=0;
RUN;
/* %MEND;
%KOYCK(0.5,HL1);*/

DATA STOCK_1112 (DROP=I);
	SET DEEPD.INFERRED (WHERE=(SAS_DATE>='1-JAN-2011'D AND SAS_DATE<'1-JAN-2013'D));
	ARRAY NEWP {18}
		  CI_2_COMM_PROGRAMS_AND_CAMPAIGNS CI_1_CUSTOMER_RESOURCES CI_3_MEDICAL_EDUCATION CI_6_SAMPLES_COUPONS_VOUCHERS 
		  SCI_2_ADVERTISING_PROGRAMS SCI_2_MCM_CAMPAIGN_EXECUTION SCI_1_DISEASE_TREATMENT_RSCRS SCI_1_PRODUCT_PROMO_RESOURCES 
		  SCI_3_LECTURE_PROGRAMS SCI_3_MMFS SCI_6_COUPONS_VOUCHERS SCI_6_PRODUCT_SAMPLES SCI_6_SAMPLES_DIST_FULFILLMENT TOTAL_PROMO
		  SCI_DIRECT DETAILS SAMPLES MEDIA_DRF;
	ARRAY STOCKS {18}
		  STK&HALFLF._C_2_CPCS STK&HALFLF._C_1_CRS STK&HALFLF._C_3_ME STK&HALFLF._C_6_SCVS STK&HALFLF._SC_2_AP STK&HALFLF._SC_2_MCM_CE
		  STK&HALFLF._SC_1_DTRS STK&HALFLF._SC_1_PPRS STK&HALFLF._SC_3_LPS STK&HALFLF._SC_3_MMFS STK&HALFLF._SC_6_CV STK&HALFLF._SC_6_PS
		  STK&HALFLF._SC_6_SAMFUL STK&HALFLF._TOTAL_C STK&HALFLF._SC_DIRECT STK&HALFLF._DETAILS STK&HALFLF._SAMPLES 
          STK&HALFLF._MEDIA_DRF;
	RETAIN STOCKS;
	DO I=1 TO DIM(NEWP);
		IF SAS_DATE='1-JAN-2011'D THEN STOCKS(I)=0;
		STOCKS(I)=NEWP(I) + &DECAY. * STOCKS(I);
	END;
	STK&HALFLF._SC_DIRECT2=STK&HALFLF._SC_DIRECT*STK&HALFLF._SC_DIRECT;
	IF '1-JAN-2011'D <= SAS_DATE <= '1-FEB-2011'D THEN FIRST2=1; ELSE FIRST2=0;
	/*IF SAS_DATE = '1-APR-2010'D THEN COMET=1; ELSE COMET=0;*/
RUN;

/*
*store as permanent datasets;
data deepd.stock_0912; set stock_0912; run; * has inferred data for 09 and 10 for CI and SCI fields;
data deepd.stock_1112; set stock_1112; run;
*/

* correlation between fields;
proc corr data=stock_0912;
  var NRX_NPA SCI_1_DISEASE_TREATMENT_RSCRS SCI_1_PRODUCT_PROMO_RESOURCES  SCI_2_ADVERTISING_PROGRAMS SCI_2_MCM_CAMPAIGN_EXECUTION 
	  SCI_3_LECTURE_PROGRAMS SCI_3_MMFS SCI_6_COUPONS_VOUCHERS SCI_6_PRODUCT_SAMPLES SCI_6_SAMPLES_DIST_FULFILLMENT TOTAL_PROMO
	  SCI_DIRECT DETAILS SAMPLES MEDIA_DRF
      STK1_SC_1_DTRS STK1_SC_1_PPRS STK1_SC_2_AP STK1_SC_2_MCM_CE 
      STK1_SC_3_LPS STK1_SC_3_MMFS STK1_SC_6_CV STK1_SC_6_PS
	  STK1_SC_6_SAMFUL STK1_TOTAL_C STK1_SC_DIRECT STK1_DETAILS STK1_SAMPLES STK1_MEDIA_DRF;
run;
proc corr data=stock_1112;
  var NRX_NPA SCI_1_DISEASE_TREATMENT_RSCRS SCI_1_PRODUCT_PROMO_RESOURCES  SCI_2_ADVERTISING_PROGRAMS SCI_2_MCM_CAMPAIGN_EXECUTION 
	  SCI_3_LECTURE_PROGRAMS SCI_3_MMFS SCI_6_COUPONS_VOUCHERS SCI_6_PRODUCT_SAMPLES SCI_6_SAMPLES_DIST_FULFILLMENT TOTAL_PROMO
	  SCI_DIRECT DETAILS SAMPLES MEDIA_DRF
      STK1_SC_1_DTRS STK1_SC_1_PPRS STK1_SC_2_AP STK1_SC_2_MCM_CE 
      STK1_SC_3_LPS STK1_SC_3_MMFS STK1_SC_6_CV STK1_SC_6_PS
	  STK1_SC_6_SAMFUL STK1_TOTAL_C STK1_SC_DIRECT STK1_DETAILS STK1_SAMPLES STK1_MEDIA_DRF;
run;



/* PROC CORR DATA=STOCK; VAR NRX: TRX: STK:; RUN;
PROC CORR DATA=STOCK; VAR NRX: TRX: CI: SCI: TOTAL_PROMO DETAILS SAMPLES; RUN;
*/

PROC PLOT DATA=STOCK; PLOT NRX_GRL * NRX_NPA; RUN; QUIT;
