PROC PRINTTO LOG="\\wpushh01\dinfopln\PRA\DTC\NuvaRing\2011 profit plan\SAS Logs and Lists\11 create market weeks cross product.LOG" NEW
			PRINT="\\wpushh01\dinfopln\PRA\DTC\NuvaRing\2011 profit plan\SAS Logs and Lists\11 create market weeks cross product.LST" NEW;
* CREATE A CROSS PRODUCT OF ALL POSSIBLE MARKET-WEEKS;

LIBNAME DTC "\\WPUSHH01\DINFOPLN\PRA\DTC\NuvaRing\2011 profit plan\SAS datasets";
LIBNAME NEWIN "\\WPUSHH01\DINFOPLN\PRA\DTC\NuvaRing\2011 profit plan\SAS datasets";

* CREATE DUMMY DATASET WHICH INCLUDES ONE OBS PER WEEK AND A WEEK NUMBER;
	* USE NATIONAL FILE FOR EFFICIENCY;

PROC SORT DATA=NEWIN.NATL_TV_MM (KEEP=REPORT_PERIOD MONTH YEAR) OUT=TWEEKS1 NODUPKEY; 
	BY REPORT_PERIOD; RUN;

* QC;
proc sort data=newin.locl_tv_mm (keep=report_period month year) out=chk nodupkey;
  by report_period; run;

DATA MISSING;
    INFORMAT REPORT_PERIOD DATE9.;
	FORMAT REPORT_PERIOD DATE9. MONTH YEAR BEST12.;
	INPUT YEAR MONTH REPORT_PERIOD;
	DATALINES;
	2010 1 25JAN2010
	;	
RUN;

PROC PRINT DATA=MISSING; RUN;

DATA TWEEKS2; SET TWEEKS1 MISSING; BY REPORT_PERIOD; FORMAT MONYY MONYY5.; MONYY=(MDY(MONTH,1,YEAR));
RUN;

PROC SORT DATA=TWEEKS2 NODUPKEY; BY REPORT_PERIOD; RUN;

DATA DTC.WEEKS_JUN10; SET TWEEKS2;
	*if _N_=1 then delete; /* 28DEC2009 date is in History data. However retain this from curr data than the history data */
	WEEK=_N_+154; MONTHLABEL=PUT((MDY(MONTH,1,YEAR)),MONYY5.); RUN;

PROC PRINT DATA=DTC.WEEKS_JUN10 (OBS=10); RUN;

* CREATE DUMMY DATASET WHICH INCLUDES ONE OBS PER MARKET;

PROC SORT DATA= NEWIN.LOCL_TV_MM (KEEP=MARKET) OUT=DTC.MARKETS_JUN10 NODUPKEY; 
	BY MARKET; RUN;

PROC PRINT DATA=DTC.MARKETS_JUN10 (OBS=10); RUN;

* CREATE A CROSS PRODUCT OF ALL POSSIBLE MARKET-WEEKS;
PROC SQL;
    CREATE TABLE DTC.MARKET_WEEKS_JUN10 AS
    SELECT MARKET, MONYY, REPORT_PERIOD, WEEK
    FROM DTC.MARKETS_JUN10, DTC.WEEKS_JUN10; QUIT;

PROC PRINT DATA=DTC.MARKET_WEEKS_JUN10 (OBS=10); RUN;

PROC SORT DATA=DTC.MARKET_WEEKS_JUN10; BY MARKET REPORT_PERIOD; RUN;

PROC FREQ DATA=DTC.MARKET_WEEKS_JUN10; TABLES REPORT_PERIOD*WEEK/LIST MISSING; RUN;

PROC PRINTTO;
QUIT;
