***************************************************************************;
* - MERGE NIELSEN DATA TO CROSS-PRODUCT TABLE, CREATE WEIGHTED TRPS (BY    ;
*   DURATION) AND FURTHER WEIGHT TRPS TO CREATE WEEKLY ADSTOCK FOR CURRENT ;
*   ANALYSIS PERIOD FOR CONJECTURED VALUES OF DECAY                        ;
* - SUM TO MARKET-MONTH LEVEL                                              ;
***************************************************************************;

LIBNAME DTC "\\WPUSHH01\DINFOPLN\PRA\DTC\NuvaRing\2010 profit plan\SAS datasets";
LIBNAME DTC1 "\\WPUSHH01\DINFOPLN\PRA\DTC\NuvaRing\2010 profit plan\SAS datasets";

OPTIONS MLOGIC MPRINT SYMBOLGEN;

* CREATE WEEKLY ADSTOCK VALUES FOR CURRENT WEEK, SUM TO VALUE OF <CURRENT> MACRO VAR;
* SPECIFY CURRENT ANALYSIS MONTHS IN MMMYY FORMAT;
* MACRO VARIABLE DEFINITIONS;
* PROD=PRODUCT;
* AGE=TARGET AGE GROUP;
* CURRENT=MONTHS & YEAR IN MMMYY FORMAT;
* NAME=SUFFIX FOR FINAL SAS FILENAME;

PROC CONTENTS DATA=DTC.WEEKLY_LOCAL_WEIGHTED_GRPS; RUN;

%LET ADJUST=1;* # WEEKS OF TRPS TO MANIPULATE BEFORE DECAYING;

%MACRO WEIGHT (PROD,AGE,CURRENT,NAME); 

LIBNAME &PROD "\\WPUSHH01\DINFOPLN\PRA\DTC\NUVARING\2010 Profit Plan\SAS Datasets\&PROD\DECAY";


* IDENTIFY HIGHEST WEEK NUMBER IN CURRENT MONTH;
PROC SORT DATA=DTC1.WEEKS_DEC09 OUT=TWEEKS3; BY MONYY WEEK; RUN;
DATA _NULL_; SET TWEEKS3;BY MONYY; IF LAST.MONYY AND 
	MONTHLABEL=&CURRENT THEN DO; CALL SYMPUT('CWEEK',STRIP(WEEK)); END; RUN; QUIT;

%PUT CURRENT PERIOD WEEK IS &CWEEK; RUN;

DATA &PROD.SUM4 (KEEP=MARKET REPORT_PERIOD MONTH WEEK NWEEK RELWEEK
                 WTRPS_&AGE: WCTRPS_&AGE ADSTOCK_&AGE: CADSTOCK_&AGE: 
				 WZTRPS_&AGE WLTRPS_&AGE WSTRPS_&AGE WRTRPS_&AGE WVTRPS_&AGE
				 LADSTOCK_&AGE: ZADSTOCK_&AGE: SADSTOCK_&AGE: RADSTOCK_&AGE: 
				 VADSTOCK_&AGE: ADSTOCK_PR_: CADSTOCK_PR_: LADSTOCK_PR_: ZADSTOCK_PR_:
                 SADSTOCK_PR_: RADSTOCK_PR_:);
        SET  DTC.WEEKLY_LOCAL_WEIGHTED_GRPS (WHERE=(WEEK<=&CWEEK) IN=W);

        IF W; * ONLY DO THIS IF CURRENT WEEK OR EARLIER;

        * NOTE: RELWEEK IS WEEK NUMBER FOR EXPONENTIATING DECAY VALUE;

		NWEEK=WEEK-&CWEEK; * THIS IS WEEK COUNTER - ZERO FOR CURRENT, -1 FOR FIRST PREVIOUS, ETC.;
        RELWEEK=(WEEK-(&CWEEK-&ADJUST+1)); * RELWEEK IS ZERO FOR WEEKS THAT DO NOT CONTRIBUTE TO ADSTOCK;
                IF RELWEEK>0 THEN RELWEEK=0;   * (SO, ZERO FOR &ADJUST WEEKS INCLDNG LAST WEEK IN &CURRENT);

        %MACRO ADSTOCK(DECAY,HLIFE);     * CREATES ADSTOCK TRPS FOR CONJECTURED DECAY VALUES;

                ADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WTRPS_&AGE;

                CADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WCTRPS_&AGE;

                LADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WLTRPS_&AGE;

                ZADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WZTRPS_&AGE;

                SADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WSTRPS_&AGE;

                RADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WRTRPS_&AGE; 

                VADSTOCK_&AGE._&HLIFE=(&DECAY**ABS(RELWEEK))*WVTRPS_&AGE;

				ADSTOCK_PR_&HLIFE=	(&DECAY**ABS(RELWEEK))*NPRINT_GRP;
				CADSTOCK_PR_&HLIFE=(&DECAY**ABS(RELWEEK))*CPRINT_GRP;
				LADSTOCK_PR_&HLIFE=(&DECAY**ABS(RELWEEK))*LPRINT_GRP;
				ZADSTOCK_PR_&HLIFE=(&DECAY**ABS(RELWEEK))*ZPRINT_GRP;
				SADSTOCK_PR_&HLIFE=(&DECAY**ABS(RELWEEK))*SPRINT_GRP;
				RADSTOCK_PR_&HLIFE=(&DECAY**ABS(RELWEEK))*RPRINT_GRP; 

        %MEND;
		%ADSTOCK(0.5000,1) ;
        %ADSTOCK(0.7071,2) ;
        %ADSTOCK(0.7937,3) ;
        %ADSTOCK(0.8409,4) ;
        %ADSTOCK(0.8706,5) ;
        %ADSTOCK(0.8909,6) ;
        %ADSTOCK(0.9057,7) ;
        %ADSTOCK(0.9170,8) ;
        %ADSTOCK(0.9259,9) ;
        %ADSTOCK(0.9330,10) ;
        %ADSTOCK(0.9389,11) ;
        %ADSTOCK(0.9439,12) ;
        %ADSTOCK(0.9481,13) ;
        %ADSTOCK(0.9517,14) ; 
		%ADSTOCK(0.9548,15);
		%ADSTOCK(0.9576,16);
		%ADSTOCK(0.9600, 17);
		%ADSTOCK(0.9622, 18);
		%ADSTOCK(0.9642, 19);
		%ADSTOCK(0.9659, 20);
		%ADSTOCK(0.9675, 21);
		%ADSTOCK(0.9690, 22);
		%ADSTOCK(0.9703, 23);
		%ADSTOCK(0.9715, 24);

        RUN;

PROC PRINT DATA=&PROD.SUM4 (WHERE=(MARKET="ALBANY-SCHENECTADY-TROY" AND -8<NWEEK<=0));
        VAR MARKET REPORT_PERIOD WEEK NWEEK RELWEEK
                    WTRPS_&AGE: ADSTOCK_&AGE: ADSTOCK_PR_:
					WCTRPS_&AGE CADSTOCK_&AGE: CADSTOCK_PR_:
					WLTRPS_&AGE LADSTOCK_&AGE: LADSTOCK_PR_:
					WZTRPS_&AGE ZADSTOCK_&AGE: ZADSTOCK_PR_:
					WSTRPS_&AGE SADSTOCK_&AGE: SADSTOCK_PR_:
					WRTRPS_&AGE RADSTOCK_&AGE: RADSTOCK_PR_:
                    WVTRPS_&AGE VADSTOCK_&AGE: ;
RUN;

* SUM TO DMA AND MONTH;

PROC MEANS DATA=&PROD.SUM4 NWAY SUM NOPRINT;
BY MARKET;
VAR ADSTOCK_&AGE: CADSTOCK_&AGE: LADSTOCK_&AGE: ZADSTOCK_&AGE: SADSTOCK_&AGE: RADSTOCK_&AGE:  VADSTOCK_&AGE:
ADSTOCK_PR_: CADSTOCK_PR_: LADSTOCK_PR_: ZADSTOCK_PR_: SADSTOCK_PR_: RADSTOCK_PR_:;
OUTPUT OUT=&PROD..ADSTOCK7_&NAME (DROP=_TYPE_ _FREQ_) SUM=;
RUN;

PROC PRINT DATA=&PROD..ADSTOCK7_&NAME (OBS=4);
RUN;

%MEND;


%WEIGHT(NUVA,F1849,('JAN07'),JAN07);
%WEIGHT(NUVA,F1849,('FEB07'),FEB07);
%WEIGHT(NUVA,F1849,('MAR07'),MAR07);
%WEIGHT(NUVA,F1849,('APR07'),APR07);
%WEIGHT(NUVA,F1849,('MAY07'),MAY07);
%WEIGHT(NUVA,F1849,('JUN07'),JUN07);
%WEIGHT(NUVA,F1849,('JUL07'),JUL07);
%WEIGHT(NUVA,F1849,('AUG07'),AUG07);
%WEIGHT(NUVA,F1849,('SEP07'),SEP07);
%WEIGHT(NUVA,F1849,('OCT07'),OCT07);
%WEIGHT(NUVA,F1849,('NOV07'),NOV07);
%WEIGHT(NUVA,F1849,('DEC07'),DEC07);

%WEIGHT(NUVA,F1849,('JAN08'),JAN08);
%WEIGHT(NUVA,F1849,('FEB08'),FEB08);
%WEIGHT(NUVA,F1849,('MAR08'),MAR08);
%WEIGHT(NUVA,F1849,('APR08'),APR08);
%WEIGHT(NUVA,F1849,('MAY08'),MAY08);
%WEIGHT(NUVA,F1849,('JUN08'),JUN08);
%WEIGHT(NUVA,F1849,('JUL08'),JUL08);
%WEIGHT(NUVA,F1849,('AUG08'),AUG08);
%WEIGHT(NUVA,F1849,('SEP08'),SEP08);
%WEIGHT(NUVA,F1849,('OCT08'),OCT08);
%WEIGHT(NUVA,F1849,('NOV08'),NOV08);
%WEIGHT(NUVA,F1849,('DEC08'),DEC08);

%WEIGHT(NUVA,F1849,('JAN09'),JAN09);
%WEIGHT(NUVA,F1849,('FEB09'),FEB09);
%WEIGHT(NUVA,F1849,('MAR09'),MAR09);
%WEIGHT(NUVA,F1849,('APR09'),APR09);
%WEIGHT(NUVA,F1849,('MAY09'),MAY09);
%WEIGHT(NUVA,F1849,('JUN09'),JUN09);
%WEIGHT(NUVA,F1849,('JUL09'),JUL09);
%WEIGHT(NUVA,F1849,('AUG09'),AUG09);
%WEIGHT(NUVA,F1849,('SEP09'),SEP09);
%WEIGHT(NUVA,F1849,('OCT09'),OCT09);
%WEIGHT(NUVA,F1849,('NOV09'),NOV09);
%WEIGHT(NUVA,F1849,('DEC09'),DEC09);
