LIBNAME DECAY "\\WPUSHH01\DINFOPLN\PRA\DTC\NUVARING\2011 PROFIT PLAN\SAS DATASETS\NUVA\DECAY";
PROC CONTENTS DATA=DECAY.ADSTOCK7 VARNUM; RUN;
PROC PRINT DATA=DECAY.ADSTOCK7 (OBS=9); RUN;
PROC MEANS DATA=DECAY.ADSTOCK7 (DROP=ADSTOCK_PR: CADSTOCK_PR: LADSTOCK_PR: 
				  				     ZADSTOCK_PR: SADSTOCK_PR: RADSTOCK_PR:) SUM;
	VAR _NUMERIC_;
	RUN;
PROC MEANS DATA=DECAY.ADSTOCK7 SUM;
	VAR ADSTOCK_PR: CADSTOCK_PR: LADSTOCK_PR: ZADSTOCK_PR: SADSTOCK_PR: RADSTOCK_PR:; RUN;
DATA ADSTOCK7_PERIODS; SET DECAY.ADSTOCK7;
	IF YEAR<2010 THEN PERIOD="HISTORICAL"; ELSE PERIOD="CURRENT"; RUN;
PROC MEANS DATA=ADSTOCK7_PERIODS SUM;
	VAR ADSTOCK_PR: CADSTOCK_PR: LADSTOCK_PR: ZADSTOCK_PR: SADSTOCK_PR: RADSTOCK_PR:;
	CLASS PERIOD; RUN;
